services:
  postgres:
    environment:
      - PGDATA=/pgtmpfs
    tmpfs:
      - /pgtmpfs

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - KOMPANION_VERSION=integration

  integration:
    build:
      context: .
      dockerfile: integration-test/Dockerfile
    container_name: integration
    image: integration
    depends_on:
      - app
