// Code generated by MockGen. DO NOT EDIT.
// Source: /home/deploy/kompanion/internal/highlight/interfaces.go

// Package highlight_test is a generated GoMock package.
package highlight_test

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/vanadium23/kompanion/internal/entity"
	highlight "github.com/vanadium23/kompanion/internal/highlight"
)

// MockHighlightRepo is a mock of HighlightRepo interface.
type MockHighlightRepo struct {
	ctrl     *gomock.Controller
	recorder *MockHighlightRepoMockRecorder
}

// MockHighlightRepoMockRecorder is the mock recorder for MockHighlightRepo.
type MockHighlightRepoMockRecorder struct {
	mock *MockHighlightRepo
}

// NewMockHighlightRepo creates a new mock instance.
func NewMockHighlightRepo(ctrl *gomock.Controller) *MockHighlightRepo {
	mock := &MockHighlightRepo{ctrl: ctrl}
	mock.recorder = &MockHighlightRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHighlightRepo) EXPECT() *MockHighlightRepoMockRecorder {
	return m.recorder
}

// GetByDocumentID mocks base method.
func (m *MockHighlightRepo) GetByDocumentID(ctx context.Context, documentID string) ([]entity.Highlight, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDocumentID", ctx, documentID)
	ret0, _ := ret[0].([]entity.Highlight)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDocumentID indicates an expected call of GetByDocumentID.
func (mr *MockHighlightRepoMockRecorder) GetByDocumentID(ctx, documentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDocumentID", reflect.TypeOf((*MockHighlightRepo)(nil).GetByDocumentID), ctx, documentID)
}

// GetDocumentsByDevice mocks base method.
func (m *MockHighlightRepo) GetDocumentsByDevice(ctx context.Context, deviceName string) ([]highlight.DocumentInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDocumentsByDevice", ctx, deviceName)
	ret0, _ := ret[0].([]highlight.DocumentInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDocumentsByDevice indicates an expected call of GetDocumentsByDevice.
func (mr *MockHighlightRepoMockRecorder) GetDocumentsByDevice(ctx, deviceName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDocumentsByDevice", reflect.TypeOf((*MockHighlightRepo)(nil).GetDocumentsByDevice), ctx, deviceName)
}

// Store mocks base method.
func (m *MockHighlightRepo) Store(ctx context.Context, h entity.Highlight) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, h)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockHighlightRepoMockRecorder) Store(ctx, h interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockHighlightRepo)(nil).Store), ctx, h)
}

// MockHighlight is a mock of Highlight interface.
type MockHighlight struct {
	ctrl     *gomock.Controller
	recorder *MockHighlightMockRecorder
}

// MockHighlightMockRecorder is the mock recorder for MockHighlight.
type MockHighlightMockRecorder struct {
	mock *MockHighlight
}

// NewMockHighlight creates a new mock instance.
func NewMockHighlight(ctrl *gomock.Controller) *MockHighlight {
	mock := &MockHighlight{ctrl: ctrl}
	mock.recorder = &MockHighlightMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHighlight) EXPECT() *MockHighlightMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockHighlight) Fetch(ctx context.Context, documentID string) ([]entity.Highlight, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, documentID)
	ret0, _ := ret[0].([]entity.Highlight)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockHighlightMockRecorder) Fetch(ctx, documentID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockHighlight)(nil).Fetch), ctx, documentID)
}

// GetDocumentsByDevice mocks base method.
func (m *MockHighlight) GetDocumentsByDevice(ctx context.Context, deviceName string) ([]highlight.DocumentInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDocumentsByDevice", ctx, deviceName)
	ret0, _ := ret[0].([]highlight.DocumentInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDocumentsByDevice indicates an expected call of GetDocumentsByDevice.
func (mr *MockHighlightMockRecorder) GetDocumentsByDevice(ctx, deviceName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDocumentsByDevice", reflect.TypeOf((*MockHighlight)(nil).GetDocumentsByDevice), ctx, deviceName)
}

// Sync mocks base method.
func (m *MockHighlight) Sync(ctx context.Context, documentID string, highlights []entity.Highlight, deviceName string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", ctx, documentID, highlights, deviceName)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sync indicates an expected call of Sync.
func (mr *MockHighlightMockRecorder) Sync(ctx, documentID, highlights, deviceName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockHighlight)(nil).Sync), ctx, documentID, highlights, deviceName)
}
